[theme]
theme = "plain"

[[block]]
block = "focused_window"
format = " $title.str(max_w:40) |"

[[block]]
block = "battery"
format = " $icon $percentage "
full_format = " $icon $percentage "
not_charging_format = " $icon $percentage "

[[block]]
block = "cpu"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "

[[block]]
block = "sound"
format = " $icon{ $volume.eng(w:2) |}"
max_vol = 100
[block.icons_overrides]
volume_muted = "[MUTED] "

[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%-d.%-m.%Y %-H:%M') "
